CREATE TABLE IF NOT EXISTS `ast_trunk` (
  `HIID` BIGINT(20) NOT NULL DEFAULT '0',
	`trID` INT(11) NOT NULL,
	`Aid` INT(11) NOT NULL DEFAULT '0',
	`trName` VARCHAR(50) NOT NULL,
	`uniqName` VARCHAR(55) NULL DEFAULT NULL,
	`template` VARCHAR(50) NOT NULL DEFAULT '',
	`secret` VARCHAR(50) NULL DEFAULT NULL,
	`context` VARCHAR(50) NOT NULL DEFAULT '',
	`callgroup` INT(4) UNSIGNED NULL DEFAULT '0',
	`pickupgroup` INT(4) UNSIGNED NULL DEFAULT '0',
	`callerid` VARCHAR(80) NOT NULL DEFAULT '',
	`host` VARCHAR(80) NULL DEFAULT NULL,
	`nat` INT(11) NULL DEFAULT NULL,
	`fromuser` VARCHAR(40) NULL DEFAULT NULL,
	`defaultuser` VARCHAR(40) NULL DEFAULT NULL,
	`fromdomain` VARCHAR(40) NULL DEFAULT NULL,
	`callbackextension` VARCHAR(40) NULL DEFAULT NULL,
	`port` INT(11) NULL DEFAULT NULL,
	`isServer` BIT(1) NULL DEFAULT NULL,
	`type` INT(10) NULL DEFAULT NULL,
	`directmedia` INT(11) NULL DEFAULT NULL,
	`insecure` INT(11) NULL DEFAULT NULL,
	`outboundproxy` VARCHAR(60) NULL DEFAULT NULL,
	`acl` VARCHAR(60) NULL DEFAULT NULL,
	`dtmfmode` INT(11) NULL DEFAULT NULL,
	`lines` INT(11) NULL DEFAULT '1',
	`DIDs` VARCHAR(250) NULL DEFAULT NULL,
	`ManageID` INT(11) NULL DEFAULT NULL,
	`coID` INT(11) NULL DEFAULT NULL,
	`transport` VARCHAR(50) NULL DEFAULT '103102',
	`encryption` BIT(1) NULL DEFAULT b'0',
	`avpf` BIT(1) NULL DEFAULT b'0',
	`force_avp` BIT(1) NULL DEFAULT b'0',
	`icesupport` BIT(1) NULL DEFAULT b'0',
	`videosupport` BIT(1) NULL DEFAULT b'0',
	`allow` VARCHAR(50) NULL DEFAULT '103201,103202,103203',
	`dtlsenable` BIT(1) NULL DEFAULT b'0',
	`dtlsverify` BIT(1) NULL DEFAULT b'0',
	`dtlscertfile` VARCHAR(100) NULL DEFAULT NULL,
	`dtlscafile` VARCHAR(100) NULL DEFAULT NULL,
	`dtlssetup` VARCHAR(100) NULL DEFAULT NULL,
	`isActive` BIT(1) NULL DEFAULT NULL COMMENT 'Признак активности записи',
	`Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время создания записи',
	`Changed` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Время изменения записи',
	`isReadable` BIT(1) NOT NULL DEFAULT b'1',
	`Comment` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`trID`),
	INDEX `id` (`trID`),
	INDEX `name` (`trName`),
	INDEX `Aid` (`Aid`),
	INDEX `isActive` (`isActive`),
	INDEX `isReadable` (`isReadable`),
	INDEX `Created` (`Created`),
	INDEX `HIID` (`HIID`),
	INDEX `isServer` (`isServer`),
	INDEX `type` (`type`),
	INDEX `uniqName` (`uniqName`),
	INDEX `template` (`template`),
	INDEX `secret` (`secret`),
	INDEX `context` (`context`),
	INDEX `callgroup` (`callgroup`),
	INDEX `pickupgroup` (`pickupgroup`),
	INDEX `callerid` (`callerid`),
	INDEX `host` (`host`),
	INDEX `nat` (`nat`),
	INDEX `fromuser` (`fromuser`),
	INDEX `fromdomain` (`fromdomain`),
	INDEX `callbackextension` (`callbackextension`),
	INDEX `port` (`port`),
	INDEX `directmedia` (`directmedia`),
	INDEX `outboundproxy` (`outboundproxy`),
	INDEX `insecure` (`insecure`),
	INDEX `acl` (`acl`),
	INDEX `dtmfmode` (`dtmfmode`),
	INDEX `lines` (`lines`),
	INDEX `defaultuser` (`defaultuser`),
	INDEX `DIDs` (`DIDs`),
	INDEX `ManageID` (`ManageID`),
	INDEX `coID` (`coID`),
	INDEX `transport` (`transport`),
	INDEX `encryption` (`encryption`),
	INDEX `avpf` (`avpf`),
	INDEX `force_avp` (`force_avp`),
	INDEX `icesupport` (`icesupport`),
	INDEX `videosupport` (`videosupport`),
	INDEX `allow` (`allow`),
	INDEX `dtlsenable` (`dtlsenable`),
	INDEX `dtlsverify` (`dtlsverify`),
	INDEX `dtlscertfile` (`dtlscertfile`),
	INDEX `dtlscafile` (`dtlscafile`),
	INDEX `dtlssetup` (`dtlssetup`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
--
