CREATE TABLE IF NOT EXISTS `ast_queues` (
	`HIID` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`queID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID очереди',
	`Aid` INT(11) NOT NULL COMMENT 'ID клиента',
	`name` VARCHAR(128) NOT NULL,
	`musiconhold` VARCHAR(128) NULL DEFAULT NULL,
	`announce` VARCHAR(128) NULL DEFAULT NULL,
	`context` VARCHAR(128) NULL DEFAULT NULL,
	`timeout` INT(11) NULL DEFAULT NULL,
	`monitor_join` TINYINT(1) NULL DEFAULT NULL,
	`monitor_format` VARCHAR(128) NULL DEFAULT NULL,
	`queue_youarenext` VARCHAR(128) NULL DEFAULT NULL,
	`queue_thereare` VARCHAR(128) NULL DEFAULT NULL,
	`queue_callswaiting` VARCHAR(128) NULL DEFAULT NULL,
	`queue_holdtime` VARCHAR(128) NULL DEFAULT NULL,
	`queue_minutes` VARCHAR(128) NULL DEFAULT NULL,
	`queue_seconds` VARCHAR(128) NULL DEFAULT NULL,
	`queue_lessthan` VARCHAR(128) NULL DEFAULT NULL,
	`queue_thankyou` VARCHAR(128) NULL DEFAULT NULL,
	`queue_reporthold` VARCHAR(128) NULL DEFAULT NULL,
	`announce_frequency` INT(11) NULL DEFAULT NULL,
	`announce_round_seconds` INT(11) NULL DEFAULT NULL,
	`announce_holdtime` VARCHAR(128) NULL DEFAULT NULL,
	`retry` INT(11) NULL DEFAULT NULL,
	`wrapuptime` INT(11) NULL DEFAULT NULL,
	`maxlen` INT(11) NULL DEFAULT NULL,
	`servicelevel` INT(11) NULL DEFAULT NULL,
	`strategy` VARCHAR(128) NULL DEFAULT NULL,
	`joinempty` VARCHAR(128) NULL DEFAULT NULL,
	`leavewhenempty` VARCHAR(128) NULL DEFAULT NULL,
	`eventmemberstatus` TINYINT(1) NULL DEFAULT NULL,
	`eventwhencalled` TINYINT(1) NULL DEFAULT NULL,
	`reportholdtime` TINYINT(1) NULL DEFAULT NULL,
	`memberdelay` INT(11) NULL DEFAULT NULL,
	`weight` INT(11) NULL DEFAULT NULL,
	`timeoutrestart` TINYINT(1) NULL DEFAULT NULL,
	`periodic_announce` VARCHAR(50) NULL DEFAULT NULL,
	`periodic_announce_frequency` INT(11) NULL DEFAULT NULL,
	`ringinuse` TINYINT(1) NULL DEFAULT NULL,
	`setinterfacevar` TINYINT(1) NULL DEFAULT NULL,
	`max_wait_time` INT(11) NULL DEFAULT NULL,
	`fail_destination` INT(11) NULL DEFAULT NULL,
	`fail_destdata` INT(11) NULL DEFAULT NULL,
	`fail_destdata2` VARCHAR(100) NULL DEFAULT NULL,
	`isActive` BIT(1) NOT NULL DEFAULT b'1' COMMENT 'Признак активна запись или нет',
	`Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время создания записи',
	`Changed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Время редактирования записи',
	PRIMARY KEY (`queID`),
	INDEX `Aid` (`Aid`),
	INDEX `isActive` (`isActive`),
	INDEX `name` (`name`),
	INDEX `Created` (`Created`),
	INDEX `HIID` (`HIID`),
	INDEX `fail_destdata2` (`fail_destdata2`),
	INDEX `fail_destdata` (`fail_destdata`),
	INDEX `fail_destination` (`fail_destination`),
	INDEX `max_wait_time` (`max_wait_time`),
	INDEX `setinterfacevar` (`setinterfacevar`),
	INDEX `ringinuse` (`ringinuse`),
	INDEX `periodic_announce_frequency` (`periodic_announce_frequency`),
	INDEX `timeoutrestart` (`timeoutrestart`),
	INDEX `periodic_announce` (`periodic_announce`),
	INDEX `weight` (`weight`),
	INDEX `memberdelay` (`memberdelay`),
	INDEX `reportholdtime` (`reportholdtime`),
	INDEX `eventwhencalled` (`eventwhencalled`),
	INDEX `eventmemberstatus` (`eventmemberstatus`),
	INDEX `leavewhenempty` (`leavewhenempty`),
	INDEX `joinempty` (`joinempty`),
	INDEX `strategy` (`strategy`),
	INDEX `maxlen` (`maxlen`),
	INDEX `servicelevel` (`servicelevel`),
	INDEX `wrapuptime` (`wrapuptime`),
	INDEX `retry` (`retry`),
	INDEX `announce_round_seconds` (`announce_round_seconds`),
	INDEX `announce_holdtime` (`announce_holdtime`),
	INDEX `announce_frequency` (`announce_frequency`),
	INDEX `queue_reporthold` (`queue_reporthold`),
	INDEX `queue_lessthan` (`queue_lessthan`),
	INDEX `queue_thankyou` (`queue_thankyou`),
	INDEX `queue_minutes` (`queue_minutes`),
	INDEX `queue_seconds` (`queue_seconds`),
	INDEX `queue_holdtime` (`queue_holdtime`),
	INDEX `queue_callswaiting` (`queue_callswaiting`),
	INDEX `queue_thereare` (`queue_thereare`),
	INDEX `queue_youarenext` (`queue_youarenext`),
	INDEX `monitor_format` (`monitor_format`),
	INDEX `monitor_join` (`monitor_join`),
	INDEX `timeout` (`timeout`),
	INDEX `context` (`context`),
	INDEX `announce` (`announce`),
	INDEX `musiconhold` (`musiconhold`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
