CREATE TABLE IF NOT EXISTS `ast_conference` (
	`HIID` BIGINT(20) NULL DEFAULT '0',
	`cfID` INT(11) NOT NULL DEFAULT '0',
	`Aid` INT(11) NULL DEFAULT '0',
	`cfName` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Номер для создания конференции',
	`cfDesc` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Название',
	`userPin` INT(11) NULL DEFAULT NULL COMMENT 'Пароль для входа пользователя',
	`adminPin` INT(11) NULL DEFAULT NULL COMMENT 'Пароль для входа админа',
	`langID` INT(11) NULL DEFAULT NULL COMMENT 'Язык',
	`record_id` INT(11) NULL DEFAULT NULL COMMENT 'Приветствие при входе в конференцию',
	`leaderWait` BIT(1) NULL DEFAULT b'0' COMMENT 'Ожидание основного пользователя. который запустит конференцию',
	`leaderLeave` BIT(1) NULL DEFAULT b'0' COMMENT 'Окончить конференцию, если основной пользователь вышел',
	`talkerOptimization` BIT(1) NULL DEFAULT b'0' COMMENT 'Устанавливать режим ТИШИНА, для пользователей, которые не разговаривают в данный момент',
	`talkerDetection` BIT(1) NULL DEFAULT b'0' COMMENT 'Мониторить пользователей',
	`quiteMode` BIT(1) NULL DEFAULT b'0' COMMENT 'Не проигрывать запись, когда кто то заходит/выходит',
	`userCount` BIT(1) NULL DEFAULT b'0' COMMENT 'Озвучивание кол-ва пользователей при добавлении нового пользователя',
	`userJoinLeave` BIT(1) NULL DEFAULT b'0' COMMENT 'Озвучивание, когда кто то заходит / выходит в конференции',
	`moh` BIT(1) NULL DEFAULT b'0' COMMENT 'Проигрывать music on hold, пока первый ожидает остальных',
	`mohClass` INT(11) NULL DEFAULT NULL,
	`allowMenu` BIT(1) NULL DEFAULT b'0' COMMENT 'Активация меню',
	`recordConference` BIT(1) NULL DEFAULT b'0' COMMENT 'Сохранение записи конференции',
	`maxParticipants` INT(11) NULL DEFAULT NULL,
	`muteOnJoin` BIT(1) NULL DEFAULT b'0' COMMENT 'Режим тишина у только что подключенного участника',
	`isActive` BIT(1) NULL DEFAULT b'1',
	`Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`Changed` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`cfID`),
	INDEX `HIID` (`HIID`),
	INDEX `Aid` (`Aid`),
	INDEX `cfName` (`cfName`),
	INDEX `cfDesc` (`cfDesc`),
	INDEX `userPin` (`userPin`),
	INDEX `adminPin` (`adminPin`),
	INDEX `langID` (`langID`),
	INDEX `record_id` (`record_id`),
	INDEX `leaderWait` (`leaderWait`),
	INDEX `leaderLeave` (`leaderLeave`),
	INDEX `talkerOptimization` (`talkerOptimization`),
	INDEX `talkerDetection` (`talkerDetection`),
	INDEX `quiteMode` (`quiteMode`),
	INDEX `userCount` (`userCount`),
	INDEX `userJoinLeave` (`userJoinLeave`),
	INDEX `moh` (`moh`),
	INDEX `mohClass` (`mohClass`),
	INDEX `allowMenu` (`allowMenu`),
	INDEX `recordConference` (`recordConference`),
	INDEX `maxParticipants` (`maxParticipants`),
	INDEX `muteOnJoin` (`muteOnJoin`),
	INDEX `Created` (`Created`),
	INDEX `isActive` (`isActive`)
)
COMMENT='Настройка конференций'
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
--
