CREATE TABLE IF NOT EXISTS `ast_sippeers` (
	`HIID` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`sipID` INT(11) NOT NULL AUTO_INCREMENT,
	`Aid` INT(11) NOT NULL DEFAULT '0',
	`sipName` VARCHAR(50) NOT NULL,
	`template` VARCHAR(50) NOT NULL DEFAULT '',
	`secret` VARCHAR(50) NOT NULL DEFAULT '',
	`context` VARCHAR(50) NOT NULL DEFAULT '',
	`callgroup` INT(4) UNSIGNED NULL DEFAULT '0',
	`pickupgroup` INT(4) UNSIGNED NULL DEFAULT '0',
	`callerid` VARCHAR(80) NOT NULL DEFAULT '',
	`nat` INT(11) NULL DEFAULT NULL,
	`lines` INT(11) NULL DEFAULT '1',
	`dtmfmode` INT(11) NULL DEFAULT NULL,
	`RowVersion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`emID` INT(11) NULL DEFAULT NULL,
	`transport` VARCHAR(50) NULL DEFAULT '103102',
	`encryption` BIT(1) NULL DEFAULT b'0',
	`avpf` BIT(1) NULL DEFAULT b'0',
	`force_avp` BIT(1) NULL DEFAULT b'0',
	`icesupport` BIT(1) NULL DEFAULT b'0',
	`videosupport` BIT(1) NULL DEFAULT b'0',
	`allow` VARCHAR(50) NULL DEFAULT '103201,103202,103203',
	`dtlsenable` BIT(1) NULL DEFAULT b'0',
	`dtlsverify` BIT(1) NULL DEFAULT b'0',
	`dtlscertfile` VARCHAR(100) NULL DEFAULT NULL,
	`dtlscafile` VARCHAR(100) NULL DEFAULT NULL,
	`dtlssetup` VARCHAR(100) NULL DEFAULT NULL,
  `isPrimary` BIT(1) NULL DEFAULT b'0',
  `sipType` INT(11) NULL DEFAULT NULL,
	`isActive` BIT(1) NOT NULL DEFAULT b'0',
	`Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время создания записи',
	`Changed` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Время изменения записи',
	PRIMARY KEY (`sipID`),
	INDEX `isActive` (`isActive`),
	INDEX `Created` (`Created`),
	INDEX `emID` (`emID`),
	INDEX `Aid` (`Aid`),
	INDEX `template` (`template`),
	INDEX `name` (`sipName`),
	INDEX `HIID` (`HIID`),
	INDEX `nat` (`nat`),
	INDEX `callerid` (`callerid`),
	INDEX `callgroup` (`callgroup`),
	INDEX `pickupgroup` (`pickupgroup`),
	INDEX `context` (`context`),
	INDEX `secret` (`secret`),
	INDEX `dtmfmode` (`dtmfmode`),
	INDEX `lines` (`lines`),
	INDEX `transport` (`transport`),
	INDEX `encryption` (`encryption`),
	INDEX `avpf` (`avpf`),
	INDEX `force_avp` (`force_avp`),
	INDEX `icesupport` (`icesupport`),
	INDEX `videosupport` (`videosupport`),
	INDEX `allow` (`allow`),
	INDEX `dtlsenable` (`dtlsenable`),
	INDEX `dtlsverify` (`dtlsverify`),
	INDEX `dtlscertfile` (`dtlscertfile`),
	INDEX `dtlscafile` (`dtlscafile`),
	INDEX `dtlssetup` (`dtlssetup`),
  INDEX `sipType` (`sipType`),
  INDEX `isPrimary` (`isPrimary`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
--
