CREATE TABLE IF NOT EXISTS `ccContactRecords` (
                                                  `idCR` INT(11) NOT NULL AUTO_INCREMENT,
                                                  `Aid` INT(11) NOT NULL DEFAULT '0',
                                                  `link` VARCHAR(250) NULL DEFAULT NULL,
                                                  `statusReady` INT(11) NULL DEFAULT '103801',
                                                  `DateFrom` DATETIME NULL DEFAULT NULL,
                                                  `DateTo` DATETIME NULL DEFAULT NULL,
                                                  `dcIDs` VARCHAR(250) NULL DEFAULT NULL,
                                                  `emIDs` VARCHAR(250) NULL DEFAULT NULL,
                                                  `dcStatuss` VARCHAR(250) NULL DEFAULT NULL,
                                                  `ffIDs` VARCHAR(250) NULL DEFAULT NULL,
                                                  `isMissed` BIT(1) NULL DEFAULT NULL,
                                                  `isUnique` BIT(1) NULL DEFAULT NULL,
                                                  `CallTypes` VARCHAR(250) NULL DEFAULT NULL,
                                                  `ccNames` VARCHAR(250) NULL DEFAULT NULL,
                                                  `channels` VARCHAR(250) NULL DEFAULT NULL,
                                                  `comparison` VARCHAR(250) NULL DEFAULT NULL,
                                                  `billsec` VARCHAR(250) NULL DEFAULT NULL,
                                                  `clIDs` VARCHAR(250) NULL DEFAULT NULL,
                                                  `IsOut` BIT(1) NULL DEFAULT NULL,
                                                  `id_autodials` VARCHAR(250) NULL DEFAULT NULL,
                                                  `id_scenarios` VARCHAR(250) NULL DEFAULT NULL,
                                                  `ManageIDs` VARCHAR(250) NULL DEFAULT NULL,
                                                  `target` VARCHAR(250) NULL DEFAULT NULL,
                                                  `coIDs` VARCHAR(250) NULL DEFAULT NULL,
                                                  `destination` INT(11) NULL DEFAULT NULL,
                                                  `destdata` INT(11) NULL DEFAULT NULL,
                                                  `destdata2` VARCHAR(250) NULL DEFAULT NULL,
                                                  `ContactStatuses` INT(11) NULL DEFAULT NULL,
                                                  `emID` INT(11) NULL DEFAULT NULL,
                                                  `convertFormat` INT(11) NULL DEFAULT NULL,
                                                  `isActive` BIT(1) NULL DEFAULT b'1',
                                                  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
                                                  `Changed` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                  PRIMARY KEY (`idCR`),
                                                  INDEX `statusReady` (`statusReady`),
                                                  INDEX `Aid` (`Aid`),
                                                  INDEX `isActive` (`isActive`),
                                                  INDEX `Created` (`Created`),
                                                  INDEX `DateFrom` (`DateFrom`),
                                                  INDEX `DateTo` (`DateTo`),
                                                  INDEX `dcIDs` (`dcIDs`),
                                                  INDEX `emIDs` (`emIDs`),
                                                  INDEX `dcStatuss` (`dcStatuss`),
                                                  INDEX `ffIDs` (`ffIDs`),
                                                  INDEX `isMissed` (`isMissed`),
                                                  INDEX `isUnique` (`isUnique`),
                                                  INDEX `CallTypes` (`CallTypes`),
                                                  INDEX `ccNames` (`ccNames`),
                                                  INDEX `channels` (`channels`),
                                                  INDEX `comparison` (`comparison`),
                                                  INDEX `clIDs` (`clIDs`),
                                                  INDEX `billsec` (`billsec`),
                                                  INDEX `IsOut` (`IsOut`),
                                                  INDEX `id_autodials` (`id_autodials`),
                                                  INDEX `id_scenarios` (`id_scenarios`),
                                                  INDEX `ManageIDs` (`ManageIDs`),
                                                  INDEX `target` (`target`),
                                                  INDEX `coIDs` (`coIDs`),
                                                  INDEX `destination` (`destination`),
                                                  INDEX `destdata` (`destdata`),
                                                  INDEX `destdata2` (`destdata2`),
                                                  INDEX `ContactStatuses` (`ContactStatuses`),
                                                  INDEX `emID` (`emID`),
                                                  INDEX `convertFormat` (`convertFormat`)
)
    COMMENT='Заявка на экпорт записей разговоров - массово'
    ENGINE=MyISAM
;
--
