CREATE TABLE IF NOT EXISTS `usRank` (
	`HIID` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`Aid` INT(11) NOT NULL DEFAULT '0',
	`uID` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`type` INT(11) NOT NULL DEFAULT '103001',
	`uRank` VARCHAR(200) NULL DEFAULT NULL,
	`emID` INT(11) NULL DEFAULT NULL,
	`isActive` BIT(1) NOT NULL DEFAULT b'0' COMMENT 'Признак активности записи',
	`Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`Changed` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX `uID` (`uID`),
	INDEX `emEmploy` (`emID`),
	INDEX `Created` (`Created`),
	INDEX `isActive` (`isActive`),
	INDEX `uRank` (`uRank`),
	INDEX `type` (`type`),
	INDEX `Aid` (`Aid`),
	INDEX `HIID` (`HIID`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
--
