const api = 'api';

const routes = {
    astAutodialProcess: 'ast/autodial/process',
    astCallback: 'ast/callback',
    astConference: 'ast/conference',
    astCustomDestination: 'ast/custom/destination',
    astCdr: 'ast/cdr',
    astEvents: 'ast/events',
    astIVREntries: 'ast/ivr/items',
    astIVRConfig: 'ast/ivr',
    astMonitoring: 'ast/monitoring',
    astQueue: 'ast/queues',
    astQueueMember: 'ast/queues/members',
    astPools: 'ast/pools',
    astPoolList: 'ast/pool/items',
    astRecall: 'ast/recall',
    astRecord: 'ast/records',
    astRouteIncoming: 'ast/route/incoming',
    astRouteOutgoing: 'ast/route/outgoing',
    astRouteOutgoingItems: 'ast/route/outgoing/items',
    astScenario: 'ast/scenario',
    astSippeers: 'ast/sippeers',
    astTimeGroup: 'ast/time/group',
    astTimeGroupItems: 'ast/time/group/items',
    astTrunk: 'ast/trunks',
    astTts: 'ast/tts',
    astTtsFields: 'ast/tts/fields',
    astUpdate: 'ast/update',
    ccComment: 'cc/comments',
    ccCommentList: 'cc/comments/list',
    ccContact: 'cc/contacts',
    crmClient: 'crm/clients',
    crmClientEx: 'crm/clients/ex',
    crmClientProduct: 'crm/products',
    crmCompany: 'crm/company',
    crmOrg: 'crm/orgs',
    crmContact: 'crm/contacts',
    crmAddress: 'crm/address',
    crmStatus: 'crm/status',
    crmTag: 'crm/tags',
    crmTagList: 'crm/taglist',
    crmResponsible: 'crm/responsible',
    dcDoc: 'dc/docs',
    dcType: 'dc/types',
    dcDocTemplate: 'dc/templates',
    emEmploy: 'em/employees',
    emEmployStatus: 'em/employees/status',
    emClient: 'em/clients',
    emEmployEx: 'em/employees/ex',
    emRole: 'em/roles',
    fmForm: 'dc/forms',
    fmFormItem: 'dc/forms/items',
    fmFormType: 'dc/formtypes',
    fmQuestion: 'dc/questions',
    fmQuestionItem: 'dc/questions/items',
    fsBase: 'crm/bases',
    fsFile: 'crm/files',
    fsTemplate: 'crm/templates',
    fsTemplateItem: 'crm/templates/items',
    hClient: 'h/client',
    hEmploy: 'h/employ',
    mpIntegrationList: 'mp/marketplace/list',
    mpIntegrationInstall: 'mp/marketplace/install',
    regPrefix: 'reg/prefix',
    regPrefixTitle: 'reg/prefix/title',
    regRegion: 'reg/regions',
    regArea: 'reg/areas',
    regCountry: 'reg/countries',
    regOperator: 'reg/operators',
    regValidation: 'reg/validation',
    regLocation: 'reg/locations',
    sfInvoice: 'dc/invoices',
    sfInvoiceItem: 'dc/invoices/items',
    slDeal : 'dc/deals',
    slDealItem: 'dc/deals/items',
    smsSms: 'sms',
    stBrand: 'dc/brands',
    stCategory: 'dc/categories',
    stProduct: 'dc/products',
    pchPayment: 'dc/payments',
    usEnum: 'us/enums',
    usRank: 'us/rank',
    usSequence: 'us/sequence',
    usServer: 'us/server',
    usComment: 'us/comments',
    usFavorite: 'us/favorites',
    usMeasure: 'us/measures',
};

const result = {};
for (var k in routes) {
  result[k] = `/${api}/${routes[k]}`;
}
module.exports = result;
