DROP FUNCTION IF EXISTS fn_GetToken;
DELIMITER $$
CREATE FUNCTION fn_GetToken()
RETURNS VARCHAR(100)
BEGIN
  DECLARE $token      VARCHAR(100);
  --
  SET $token = SUBSTRING(SHA1(RAND()) FROM 1 FOR 25);
  --
  RETURN $token;
END $$
DELIMITER ;
--
