<?php
    function callback($ARG1, $ARG2, $link)
    {
        $file   = $ARG1."extensions/db_callback.ael";
        $result = c_mysqli_call($link, 'ast_GetCallbackClear', 'NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL');

        $out_data = $in_data = array();
        if(file_exists($file))
            $in_data = file($file);
        else
            $in_data = '';

        $struct = array();
        foreach ($result as $info)
        {
            $struct[$info['Aid']]['info'][$info['cbID']] = $info;
            $struct[$info['Aid']]['Aid'] = $info['Aid'];
        }
        shell_exec("rm -f $file");
        if (count($struct) > 0)
        {
            file_put_contents($file,"\n", FILE_APPEND);
            file_put_contents($file,"/*   Do not edit this file, file update from MySQL   */\n", FILE_APPEND);
            file_put_contents($file,"\n", FILE_APPEND);
            //start context
            foreach ($struct as $context)
            {
                foreach ($context['info'] as $data)
                {
                    file_put_contents($file,'context db_callback_' . $context['Aid'] .'_'.$data['cbID'] . " { \n", FILE_APPEND);
                    file_put_contents($file,'     s => { MSet(isFirstClient='.((isset($data['isFirstClient']) && $data['isFirstClient'] == 1) ? 'true' : 'false').',CallType=101319); &postCallincard();  Congestion; Hangup; } '."\n", FILE_APPEND);
                    file_put_contents($file,'     h => { System(sleep '.((isset($data['timeout']) && strlen(trim($data['timeout'])>0)) ? trim($data['timeout']) : 0) .'); CallType=101319; ', FILE_APPEND);
                    file_put_contents($file,'System(${ApiOriginate} -d \'{  "Aid": '.$context['Aid'].', "phone": "${ccName}", "exten": "s", "isFirstClient": '.((isset($data['isFirstClient']) && $data['isFirstClient'] == 1) ? 'true' : 'false').', "context": "db_callback_items_' . $context['Aid'] .'_'.$data['cbID'].'" }\'); Hangup; } ', FILE_APPEND);
                    file_put_contents($file,"}\n\n", FILE_APPEND);
                    file_put_contents($file,'context db_callback_items_' . $context['Aid'] .'_'.$data['cbID'] . " { \n", FILE_APPEND);
                    file_put_contents($file, '     s => { './*destination=' . $data['destination'] . '; ' . (isset($data['destdata']) ? ('destdata=' . $data['destdata'] . '; ') : '') . (isset($data['destdata2']) ? ('destdata2=' . $data['destdata2'] . '; ') : '') */ str_replace('Answer;', 'CallType=101319;', trim(routeInfo($link, $context['Aid'], 'invalid_ivr', $data['destination'], ['destdata' => $data['destdata'], 'destdata2' => $data['destdata2']]))) . ' Hangup; } ' . "\n", FILE_APPEND);
                    file_put_contents($file,"}\n\n", FILE_APPEND);
                }
            }
            echo 'db_callback: created "'.$file .'"'."\n";
            if(file_exists($file))
                $out_data = file($file);
            else
                $out_data = '';
            return checkFile($ARG2."asterisk -rx 'ael reload'", $in_data, $out_data);
        }
        else
            return 'no changes';
    }
?>