<?php
    function conference_ael($ARG1, $ARG2, $link)
    {
        $file   = $ARG1."extensions/db_conference.ael";
        $result = c_mysqli_call($link, 'ast_GetConferenceClear', 'NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, 0, 1000');

        $out_data = $in_data = array();
        if(file_exists($file))
            $in_data = file($file);
        else
            $in_data = '';

        $struct = array();
        foreach ($result as $info)
        {
            $struct[$info['Aid']]['info'][] = $info;
            $struct[$info['Aid']]['Aid'] = $info['Aid'];
        }
        //print_r($struct);

        shell_exec("rm -f $file");
        if (count($struct) > 0)
        {
            file_put_contents($file,"\n", FILE_APPEND);
            file_put_contents($file,"/*   Do not edit this file, file update from MySQL   */\n", FILE_APPEND);
            file_put_contents($file,"\n", FILE_APPEND);
            foreach ($struct as $context)
            {
                file_put_contents($file,'context db_conference_'.$context['Aid']." { \n", FILE_APPEND);
                foreach ($context['info'] as $conference)
                {
                    if(strlen(trim($conference['adminPin']))>0 && strlen(trim($conference['userPin']))>0)
                    {
                        file_put_contents($file, '     ' . $conference['cfID'] . ' =>  { ' , FILE_APPEND);
                        file_put_contents($file, "Mset(destination=101412,destdata=".$conference['cfID'] .",adminPin=".trim($conference['adminPin']).",userPin=".trim($conference['userPin']).",CONFBRIDGE(user,announce_user_count_all)=yes,CONFBRIDGE(user,music_on_hold_when_empty)=yes); Answer; READ(PIN,conf-getpin,,,,); &Conference(); Hangup; }\n", FILE_APPEND);
                    }
                    elseif(strlen(trim($conference['adminPin'])) == 0 && strlen(trim($conference['userPin'])) == 0)
                    {
                        file_put_contents($file, '     ' . $conference['cfID'] . ' =>  { ' , FILE_APPEND);
                        file_put_contents($file, 'Mset(destination=101412,destdata='.$conference['cfID'] .'); ConfBridge(${EXTEN},,default_user,default_menu); Hangup; }' . "\n", FILE_APPEND);
                    }
                    else
                    {
                        file_put_contents($file, '     ' . $conference['cfID'] . ' =>  { Hangup; }' . "\n", FILE_APPEND);
                    }
                }
                file_put_contents($file,"     h => &postCallincard();\n", FILE_APPEND);
                file_put_contents($file,"}\n\n", FILE_APPEND);
            }

            file_put_contents($file,"macro Conference(){\n", FILE_APPEND);
            file_put_contents($file,'   if("${PIN}" == "${adminPin}"){'."\n", FILE_APPEND);
            file_put_contents($file,'       Mset(CONFBRIDGE(user,admin)=yes,CONFBRIDGE(user,marked)=yes);'."\n", FILE_APPEND);
            file_put_contents($file,'       ConfBridge(${EXTEN},,default_user,default_menu); Hangup;'."\n", FILE_APPEND);
            file_put_contents($file,'   }'."\n", FILE_APPEND);
            file_put_contents($file,'   if("${PIN}" == "${userPin}"){'."\n", FILE_APPEND);
            file_put_contents($file,'       CONFBRIDGE(user,wait_marked)=yes;'."\n", FILE_APPEND);
            file_put_contents($file,'       ConfBridge(${EXTEN},,default_user,default_menu); Hangup;'."\n", FILE_APPEND);
            file_put_contents($file,'   }'."\n", FILE_APPEND);
            file_put_contents($file,'   catch h { &postCallincard(); Hangup; }'."\n", FILE_APPEND);
            file_put_contents($file,'   return;'."\n", FILE_APPEND);
            file_put_contents($file,'}'."\n", FILE_APPEND);

            if(file_exists($file))
                $out_data = file($file);
            else
                $out_data = '';
            echo 'conference.ael: created "'.$file .'"'."\n";

            return checkFile($ARG2."asterisk -rx 'ael reload'", $in_data, $out_data);
        }
        else
            return 'no changes';
    }
?>