<?php
    function queue_ael($ARG1, $ARG2, $link)
    {
        $file       = $ARG1."extensions/db_queue.ael";
        $result = c_mysqli_call($link, 'ast_GetQueueClear', 'NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, NULL, NULL, 0, 1000');

        $out_data = $in_data = array();
        if(file_exists($file))
            $in_data = file($file);
        else
            $in_data = '';

        $struct = array();
        foreach ($result as $info)
        {
            $struct[$info['Aid']]['info'][] = $info;
            $struct[$info['Aid']]['Aid'] = $info['Aid'];
        }
        shell_exec("rm -f $file");
        if (count($struct) > 0)
        {
            file_put_contents($file,"\n", FILE_APPEND);
            file_put_contents($file,"/*   Do not edit this file, file update from MySQL   */\n", FILE_APPEND);
            file_put_contents($file,"\n", FILE_APPEND);
            foreach ($struct as $context)
            {
                file_put_contents($file,'context db_queue_'.$context['Aid']." { \n", FILE_APPEND);
                foreach ($context['info'] as $queue)
                {
                    if(isset($queue['fail_destination']))
                        file_put_contents($file, '     ' . $queue['queID'] . '  =>  { MSet(' . (isset($queue['fail_destination']) ? ('destination=' . $queue['fail_destination']) : '') . (isset($queue['fail_destdata']) ? (',destdata=' . $queue['queID']) : '') . (isset($queue['fail_destdata2']) ? (',destdata2=' . $queue['fail_destdata2']) : '') . ',GLOBAL(isQueue${ccName})=true); Queue(' . $queue['queID'] . ',${optionsIn},,,,' . $queue['max_wait_time'] . ',,Q); ' . str_replace('Set(GLOBAL(isQueue${ccName})=true); ', '', str_replace('Answer; ', '', routeInfo($link, $context['Aid'], 'invalid_ivr', $queue['fail_destination'], ['destdata' => $queue['fail_destdata']]))) . ' Return; }' . "\n", FILE_APPEND);
                    else
                        file_put_contents($file, '     ' . $queue['queID'] . '  =>  { MSet(destination=101401,destdata=' . $queue['queID'].',GLOBAL(isQueue${ccName})=true); Queue(' . $queue['queID'] . ',${optionsIn},,,,' . $queue['max_wait_time'] . ',,Q); ' . str_replace('Set(GLOBAL(isQueue${ccName})=true); ', '', str_replace('Answer; ', '', routeInfo($link, $context['Aid'], 'invalid_ivr', $queue['fail_destination'], ['destdata' => $queue['fail_destdata']]))) . ' Return; }' . "\n", FILE_APPEND);
                }

                file_put_contents($file,"}\n\n", FILE_APPEND);
            }

            if(file_exists($file))
                $out_data = file($file);
            else
                $out_data = '';
            echo 'queue.ael: created "'.$file .'"'."\n";

            return checkFile($ARG2."asterisk -rx 'ael reload'", $in_data, $out_data);
        }
        else
            return 'no changes';
    }
?>