<?php
    function record_ael($ARG1, $ARG2, $link)
    {
        $file       = $ARG1."extensions/db_record.ael";
        $result = c_mysqli_call($link, 'ast_GetRecordClear', 'NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL');

        $out_data = $in_data = array();
        if(file_exists($file))
            $in_data = file($file);
        else
            $in_data = '';

        $struct = array();
        foreach ($result as $info)
        {
            $struct[$info['Aid']]['info'][] = $info;
            $struct[$info['Aid']]['Aid'] = $info['Aid'];
        }
        shell_exec("rm -f $file");
        if (count($struct) > 0)
        {

            file_put_contents($file,"\n", FILE_APPEND);
            file_put_contents($file,"/*   Do not edit this file, file update from MySQL   */\n", FILE_APPEND);
            file_put_contents($file,"\n", FILE_APPEND);
            //start context
            foreach ($struct as $context)
            {
                file_put_contents($file,'context db_record_'.$context['Aid']." { \n", FILE_APPEND);
                foreach ($context['info'] as $record)
                        file_put_contents($file,'     '.$record['record_id'].'      =>  { Answer; Playback(${Record}'.pathinfo($record['record_source'], PATHINFO_FILENAME).'); Hangup; }'."\n", FILE_APPEND);
                file_put_contents($file,"}\n\n", FILE_APPEND);
            }

            echo 'record_ael: created "'.$file .'"'."\n";
            if(file_exists($file))
                $out_data = file($file);
            else
                $out_data = '';
            $result = checkFile($ARG2."asterisk -rx 'ael reload'", $in_data, $out_data);
            if($result != 'no changes')
                exec('yes | cp -pr /var/www/html/hapi/uploads/records /mnt/rd/');
            return $result;
        }
        else
            return 'no changes';
    }
?>