<?php
    function time_ael($ARG1, $ARG2, $link)
    {
        $file       = $ARG1."extensions/db_time.ael";
        $result = c_mysqli_call($link, 'ast_GetTimeGroupClear', 'NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL');

        $out_data = $in_data = array();
        if(file_exists($file))
            $in_data = file($file);
        else
            $in_data = '';

        $struct = array();
        foreach ($result as $info)
        {
            $struct[$info['Aid']]['info'][$info['tgID']] = $info;
            $struct[$info['Aid']]['Aid'] = $info['Aid'];
        }
        shell_exec("rm -f $file");
        if (count($struct) > 0)
        {

            file_put_contents($file,"\n", FILE_APPEND);
            file_put_contents($file,"/*   Do not edit this file, file update from MySQL   */\n", FILE_APPEND);
            file_put_contents($file,"\n", FILE_APPEND);
            //start context
            foreach ($struct as $context)
            {
                foreach ($context['info'] as $timeGroup)
                {
                    $resultItem = c_mysqli_call($link, 'ast_GetTimeGroupItemsClear', $context['Aid'].', NULL, '.$timeGroup['tgID'].', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL');
                    if(count($resultItem)>0)
                    {
                        file_put_contents($file,'context db_time_'.$context['Aid'].'_'.$timeGroup['tgID']." { \n", FILE_APPEND);
                        file_put_contents($file,'   _[+0-9A-Za-z]. => {'."\n", FILE_APPEND);
                        foreach ($resultItem as $timeItem)
                        {
                            unset($timeInfo);
                            unset($dayInfo);
                            unset($dayInfo);
                            unset($dayNumInfo);
                            unset($monthInfo);
                            unset($condition);
                            $timeInfo = $dayNumInfo = $dayInfo = $monthInfo = [];
                            if(strlen($timeItem['TimeStart'])>5)
                                $timeInfo[] = substr($timeItem['TimeStart'], 0, 5);
                            if(strlen($timeItem['TimeFinish'])>5)
                                $timeInfo[] = substr($timeItem['TimeFinish'], 0, 5);
                            if(strlen($timeItem['DayNumStart'])>0)
                                $dayNumInfo[] = strtolower($timeItem['DayNumStart']);
                            if(strlen($timeItem['DayNumFinish'])>0)
                                $dayNumInfo[] = strtolower($timeItem['DayNumFinish']);
                            if(strlen($timeItem['DayStart'])>0)
                                $dayInfo[] = strtolower($timeItem['DayStart']);
                            if(strlen($timeItem['DayFinish'])>0)
                                $dayInfo[] = strtolower($timeItem['DayFinish']);
                            if(strlen($timeItem['MonthStart'])>0)
                                $monthInfo[] = strtolower($timeItem['MonthStart']);
                            if(strlen($timeItem['MonthFinish'])>0)
                                $monthInfo[] = strtolower($timeItem['MonthFinish']);
                            $condition[] = implode('-', $timeInfo);
                            $condition[] = implode('-', $dayInfo);
                            $condition[] = implode('-', $dayNumInfo);
                            $condition[] = implode('-', $monthInfo);
                            foreach ($condition as $key => $data)
                                if(strlen($data) == 0)
                                    $condition[$key] = '*';
                            file_put_contents($file, '       ifTime('.implode('|', $condition).') {'."\n", FILE_APPEND);
                            //file_put_contents($file, '           destination=' . $timeGroup['destination'] . '; ' . (isset($timeGroup['destdata']) ? ('destdata=' . $timeGroup['destdata'] . '; ') : '') . (isset($timeGroup['destdata2']) ? ('destdata2=' . $timeGroup['destdata2'] . '; ') : '') . "\n", FILE_APPEND);
                            file_put_contents($file, '           '.routeInfo($link, $context['Aid'], 'invalid_ivr', $timeGroup['destination'],  ['destdata' => $timeGroup['destdata'], 'destdata2' => $timeGroup['destdata2']])."\n"        , FILE_APPEND);
                            file_put_contents($file, '       }'."\n"        , FILE_APPEND);
                            $timeGroup_invalid_destdata = $timeGroup['invalid_destdata'];
                            $context_Aid = $context['Aid'];
                            $timeGroup_invalid_destination = $timeGroup['invalid_destination'];
                            $timeGroup_invalid_destdata2 = $timeGroup['invalid_destdata2'];
                        }
                        if(isset($timeGroup_invalid_destdata) && strlen($timeGroup_invalid_destdata)>0)
                        {
                            file_put_contents($file,'       else'."\n"        , FILE_APPEND);
                            file_put_contents($file,'       {'."\n"        , FILE_APPEND);
                            //file_put_contents($file, '           destination=' . $timeGroup_invalid_destination . '; ' . (isset($timeGroup_invalid_destdata) ? ('destdata=' . $timeGroup_invalid_destdata . '; ') : '') . (isset($timeGroup_invalid_destdata2) ? ('destdata2=' . $timeGroup_invalid_destdata2 . '; ') : '') . "\n", FILE_APPEND);
                            file_put_contents($file,'           '.routeInfo($link, $context_Aid, 'ivr', $timeGroup_invalid_destination,  ['destdata' => $timeGroup_invalid_destdata, 'destdata2' => $timeGroup_invalid_destdata2])."\n"        , FILE_APPEND);
                            file_put_contents($file,'       }'."\n"        , FILE_APPEND);
                        }
                        file_put_contents($file,"       Hangup;\n", FILE_APPEND);
                        file_put_contents($file,"   }\n", FILE_APPEND);
                        file_put_contents($file,'   t => { goto ${ccName},1; Hangup; } '."\n", FILE_APPEND);
                        file_put_contents($file,'   i => { goto ${ccName},1; Hangup; } '."\n", FILE_APPEND);
                        file_put_contents($file,'   h => { if("${IsOut}" == "false" ) &postCallincard(); } '."\n", FILE_APPEND);
                        file_put_contents($file,"}\n\n", FILE_APPEND);
                    }
                }
            }
            echo 'time_ael: created "'.$file .'"'."\n";
            if(file_exists($file))
                $out_data = file($file);
            else
                $out_data = '';
            return checkFile($ARG2."asterisk -rx 'ael reload'", $in_data, $out_data);
        }
        else
            return 'no changes';
    }
?>